module.exports = {
 welcome:'A const binding keeps the cleaned name available without reassignment. Template literals combine that value with the fixed greeting, while trim removes only outside whitespace.',
 packing:'Multiplication calculates the total cost before subtraction changes the balance. A let binding is appropriate when the stored balance is reassigned; a negative result represents overspending.',
 initials:'Trimming and splitting on a whitespace pattern turns a name into words. Mapping each first letter and joining the results separates text cleanup from formatting.',
 temperature:'A function can express a reusable numeric transformation without touching the DOM. Multiplication and division happen before addition in the Celsius-to-Fahrenheit formula.',
 receipt:'toFixed produces a string with a predictable decimal width. Keeping the price numeric until presentation avoids mixing arithmetic with formatted text.',
 admission:'Ordered conditional branches divide ages into nonoverlapping ranges. Testing the boundary ages verifies that each visitor enters exactly one range.',
 shipping:'Logical OR expresses alternative ways to qualify. Either membership or a large enough total is sufficient; AND would incorrectly require both.',
 clamp:'Clamping keeps a value within inclusive bounds while preserving values already inside them. Combining a lower maximum and an upper minimum expresses both constraints.',
 duration:'Integer division finds whole minutes and remainder finds leftover seconds. Padding applies to the seconds string, so 65 seconds becomes 1:05 rather than 1:5.',
 slug:'Chained string methods each return a new string. A global whitespace replacement handles every run of spaces instead of replacing only the first occurrence.',
 extension:'lastIndexOf identifies the final separator, which matters for names with several dots. Checking sentinel and boundary positions prevents a missing extension from becoming a misleading suffix.',
 reading:'An empty-text guard prevents counting an empty string as a word. Ceiling rounds any partial reading minute upward so the estimate does not understate the required whole minutes.',
 discount:'Percentages become fractions by dividing by 100. Rounding at the output boundary gives a two-decimal result without converting the whole calculation into string operations.',
 leap:'The century exception makes divisibility by four insufficient. Combining the 400-year rule with the non-century rule captures the complete calendar condition.',
 range:'A loop separates initialization, continuation and step size. Checking an inclusive end before each iteration also makes a reversed range naturally produce an empty array.',
 factorial:'Multiplicative accumulation starts at one, the multiplication identity. This also handles zero factorial correctly because no loop iterations change that initial product.',
 fizzbuzz:'More specific overlapping conditions must be checked before broader ones. Building one array element per integer keeps the control flow separate from presentation.',
 squares:'map transforms every element into a corresponding result. It returns a new array, making it useful for preserving the original measurements.',
 'hot-days':'filter keeps original elements when a predicate is true. The >= comparison includes the threshold itself, and filtering preserves relative order.',
 inventory:'find returns the first matching record rather than an array of matches. A missing match is undefined, so a fallback is needed before accessing its properties.',
 basket:'reduce turns a collection into a single accumulated value. An explicit zero initial value makes the same calculation valid for an empty basket.',
 average:'Average combines a sum with a count. Returning null for an empty collection makes the absence of a measurement explicit instead of returning NaN.',
 unique:'Set preserves insertion order while dropping duplicate values. Spreading it back into an array produces a distinct list without modifying the source.',
 sort:'sort mutates its array, so a copy protects the input. A numeric comparator orders times correctly, while stable sorting preserves arrival order for ties.',
 chunk:'slice extracts a bounded section without mutating the source array. Advancing the index by the page size creates disjoint pages, including a shorter last page.',
 flatten:'Flattening removes nesting while preserving sequence and repeated items. Removing just one level matches the playlist structure without unexpectedly changing deeper data.',
 frequency:'An object can associate each word with its count. A dictionary without a prototype also handles words that would otherwise collide with inherited property names.',
 group:'Grouping builds one output array for each category. Initializing the array when the category first appears lets later records append to the same group.',
 profile:'Destructuring names the fields a function needs and can provide defaults. Those defaults apply to undefined, so intentional empty strings are preserved.',
 settings:'Object spread makes a shallow copy. Later properties win, so putting the patch last applies explicit false and zero values correctly.',
 stock:'Mapping can replace one record while retaining the rest of a collection. Copying the matching object prevents a stock edit from mutating the caller’s data.',
 intersection:'A Set makes membership checks direct and deduplicates repeated interests. Filtering the first collection preserves the order the user originally supplied.',
 anagram:'Normalization lets differently formatted strings be compared consistently. Sorting normalized characters produces the same sequence exactly when both strings contain the same character counts.',
 search:'Normalizing query and item text gives case-insensitive matching. Filtering records before mapping names separates the search decision from the output format.',
 pagination:'A one-based page number becomes a zero-based offset through multiplication. slice safely returns fewer items or an empty array at the end of a collection.',
 median:'Sorting exposes the central values in a distribution. Odd lengths have one middle value; even lengths require averaging two, and an empty collection has no median.',
 transpose:'A matrix transpose swaps the role of row and column indices. Mapping column positions to values across rows works for rectangular matrices as well as square ones.',
 'run-length':'A run is a consecutive group, not the total frequency of a character. Moving an index past the entire run ensures each character is processed only once.',
 brackets:'A stack models nested structure because the most recent opening bracket must close first. Matching counts alone would miss incorrectly nested input such as ([)].',
 query:'Encoding keys and values separately protects separators inside the data. Joining the encoded pairs afterward creates a query string without confusing data characters with syntax.',
 'date-key':'An ISO timestamp can represent a different calendar date in another offset. Converting to UTC before extracting its date makes the result independent of the device timezone.',
 'days-between':'Subtracting timestamps gives elapsed milliseconds. UTC date-only inputs avoid local daylight-saving changes when calculating whole calendar-day differences.',
 weekday:'getUTCDay returns a weekday index without using the phone’s local timezone. Sunday and Saturday occupy the two boundary values, zero and six.',
 'safe-json':'Parsing untrusted text is an operation that can throw. A try/catch boundary turns that failure into a predictable result shape the rest of the program can use.',
 'validate-record':'Collecting errors lets a form report several problems at once. Integer validation rejects fractional ages rather than relying on a comparison alone.',
 'nested-total':'Recursion reduces a nested problem to smaller instances of itself. Numbers are the base case; arrays sum the recursively calculated values of their children.',
 'binary-search':'Binary search discards half of a sorted search range after each comparison. Inclusive low and high bounds allow the loop to distinguish a match from an exhausted range.',
 intervals:'Sorting by start time makes potential overlaps adjacent. Extending the most recent merged interval handles both overlapping and touching meetings while copied inputs protect the originals.',
 diff:'Comparing both key sets detects additions as well as deletions. Property presence matters separately from value, particularly when null is a legitimate stored setting.',
 'money-split':'Integer cents avoid fractional-cent arithmetic. Dividing into a base share and distributing the remainder preserves the exact total while keeping shares at most one cent apart.',
 counter:'The numeric state and its displayed text are separate responsibilities. Updating both after every action keeps the UI consistent, including reset and lower-bound behavior.',
 mood:'Dataset attributes let markup carry a button’s associated data. One shared listener pattern can update both a visual property and a readable label for every choice.',
 'tip-ui':'Input values are strings even when their input type is numeric. Converting them before arithmetic and preventing form navigation lets the calculation remain in the current preview.',
 tasks:'createElement and textContent create safe, individual task nodes. Each node can own its removal handler, while trimming and rejecting blank input keeps the list meaningful.',
 characters:'The input event fires as text changes rather than only when focus leaves the field. Replacing the output from the current value also handles deletion and empty text.',
 'greeting-ui':'Reading the field inside the click handler uses its latest value. Normalizing before the empty check prevents spaces from being mistaken for a name.',
 theme:'classList manages visual state without rewriting the whole class string. Keeping aria-pressed in sync exposes the same toggle state to assistive technology.',
 accordion:'The hidden property is a boolean controlling visibility. aria-expanded describes the opposite state to a screen reader, so both values should change together.',
 'password-ui':'A checklist combines independent rules with logical AND. A string can satisfy length while failing the digit requirement, which is why both cases are tested.',
 'word-ui':'Whitespace patterns recognize spaces, tabs and line breaks as separators. Trimming and guarding empty text prevent extra separators from becoming phantom words.',
 tabs:'A selected tab affects both content and selection styling. Clearing the previous selection before applying the next one ensures there is only one active tab.',
 'progress-ui':'Numeric progress can be bounded independently of its presentation. CSS width requires a unit, so the same number is displayed as text and formatted as a percentage for the bar.',
 'quiz-ui':'HTML data attributes expose string values, including the text "false", which itself is truthy. An explicit comparison avoids treating every answer as correct.',
 'expense-ui':'A running total must persist outside individual click callbacks. Guarding the numeric input before accumulation prevents negative values from reducing the recorded spending.',
 'email-form':'A form submit handler covers both button and keyboard submission. This simplified pattern rejects common malformed input but does not claim to verify that an email address exists.',
 'favorites-ui':'A Set tracks whether a food has already been chosen independently of the rendered list. That state guard prevents duplicate nodes before any DOM work is done.',
 'calculator-ui':'An operation label selects a known arithmetic branch. Explicit branching handles division by zero and avoids evaluating arbitrary strings as executable code.',
 'live-filter':'Visibility can be derived directly from the latest search text. Checking every item on every input also restores items that a previous query had hidden.',
 delegation:'Events bubble from nested targets to a parent listener. closest finds the intended control even when the user taps an element inside its button.',
 'select-all':'A master checkbox controls the collection, while individual checkboxes feed state back to the master. The every predicate represents the exact meaning of “all selected.”',
 stepper:'A single index is enough to represent the current step. Deriving visibility and disabled buttons from it prevents navigation controls from drifting away from the displayed section.',
 'sort-table':'Appending an existing DOM node moves it instead of copying it. Numeric comparison sorts scores correctly while retaining the name and score in the same row.',
 'cart-ui':'Recomputing a total from current quantities avoids incremental state getting out of sync. A reduce operation combines all line totals into a single formatted result.',
 rating:'A rating selects a range rather than only one button. Deriving every star’s class from the current rating also removes stale highlights when the rating is lowered.',
 'safe-comment':'textContent interprets user input as text instead of markup. This preserves literal characters and prevents user-supplied tags from becoming active elements.',
 'storage-note':'Persistent state needs both a startup read and writes after changes. The storage API returns strings or null, making a nullish default useful for a new notebook.',
 'storage-theme':'Saving a small semantic value such as "dark" is enough to recreate a visual state later. Rendering from that value on startup completes the persistence loop.',
 'storage-list':'localStorage stores strings, so arrays require JSON serialization. Parsing in a guarded block allows a damaged saved value to recover without disabling the whole interface.',
 stopwatch:'An interval id represents the one active timer. Guarding starts and clearing that id on stop keeps elapsed seconds from accelerating after repeated clicks.',
 countdown:'A countdown needs a terminal condition as well as a repeating callback. Clearing the interval at zero prevents negative counts and makes a deliberate restart possible.',
 debounce:'Debouncing postpones work until input has been quiet for a chosen interval. Cancelling the earlier timeout ensures only the most recent value is processed.',
 toast:'A timeout describes the lifetime of temporary feedback. Replacing its timer on a new notification gives the user a full interval to read the newest message.',
 undo:'Undo history naturally uses a last-in, first-out stack. Popping removed entries reverses the order of deletion and restores the original list sequence.',
 'number-guess':'Numeric conversion makes comparisons operate on numbers rather than input strings. Separate low, high and equal branches provide feedback for every outcome.',
 'unit-ui':'A shared render function gives different UI events the same calculation path. Choosing the conversion direction from current state avoids stale results when only the unit changes.',
 'fetch-user':'fetch resolves to a Response, not the final user object. A second await reads JSON before its fields become available, even though this service is simulated locally.',
 'fetch-products':'Async data loading can feed the same array transformations as local data. Filtering before mapping keeps the price decision separate from the displayed names.',
 'fetch-status':'HTTP errors are successful transport responses with unsuccessful status codes. Checking response.ok is necessary because a 404 does not automatically enter catch.',
 'fetch-catch':'Transport failures and invalid response bodies can reject at different awaits. Keeping both inside one try/catch turns either problem into usable fallback data.',
 parallel:'Promise.all lets independent requests overlap while preserving their input ordering. Destructuring the responses makes each source explicit before combining the results.',
 retry:'A bounded retry loop gives a transient failure a second chance without retrying forever. Both a rejected request and a non-OK response need to count as failed attempts.',
 'pages-api':'Following the service’s next link avoids hard-coding a page count. A loop accumulates each page and terminates when the response explicitly says there is no next page.',
 settled:'Promise.allSettled reports every outcome instead of stopping at the first rejection. Filtering fulfilled entries retains useful data from a partially failed batch.',
 post:'A JSON POST has a method, a content type and a serialized body. The local service validates that request contract before returning the created record.',
 'module-money':'A named import binds a module’s exported function to a local name. Reusing a formatting module keeps the display rule in one place instead of duplicating it.',
 'module-stats':'Modules can expose several related functions through named exports. Composing their results into a new object reuses tested calculations without sharing mutable state.',
 'module-dynamic':'Dynamic import resolves asynchronously to a module namespace. It can load a capability where it is needed, and the local data-URL resolver preserves that behavior offline.',
 'async-ui':'A request has visible pending and settled states. Setting pending state before await and clearing it in finally prevents duplicate actions and stuck controls.',
 'race-ui':'Requests can finish in a different order from the user’s input. A monotonically increasing request id lets the interface ignore responses that no longer describe the current query.',
 'abort-ui':'AbortController communicates cancellation through a signal passed to fetch. Recognizing AbortError separately prevents cancellation from being displayed as either success or an unexpected failure.'
};
